{% set name = "flake8-blind-except" %}
{% set version = "0.2.0" %}
{% set sha256 = "02a860a1a19cb602c006a3fe0778035b0d14d3f57929b4b798bc7d6684f204e5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - pep8

test:
  imports:
    - flake8_blind_except

about:
  home: https://github.com/elijahandrews/flake8-blind-except
  license: MIT
  license_family: MIT
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE
  summary: A flake8 extension that checks for blind, catch-all except statements
  description: |
    A flake8 extension that checks for blind, catch-all except statements
  doc_url: https://github.com/elijahandrews/flake8-blind-except
  dev_url: https://github.com/elijahandrews/flake8-blind-except

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
